### ISSUE TITLE
Diligência de Plano de trabalho

### ISSUE THREAD

**Issue by matheusbsilva** [culturagovbr/sistema-nacional-cultura#116]
Eu, como gestor do ministério, gostaria de poder emitir uma diligência para a situação geral do plano de trabalho de cada ente.

**Critérios de Aceitação**
 - [x] Testes para cada camada envolvida 
 - [x] Interface para enviar a diligência #132 
 - [x] Interface de consulta de histórico
 - [x] Enviar o texto da diligência do Plano de trabalho por email #131 
 - [x] Informações sobre a diligência: 
   - [x] Data da diligência
   - [x] Texto da diligência
   - [x] Usuário que enviou a diligência
   - [x] Situação da diligência
   - [x] Tipo da Diligência #130

**Comment by decko** [comment]
# Especificação
Cada plano de trabalho do SNC deve permitir o envio de uma redação de diligencia na qual o servidor responsável possa registrar sua analise geral dos elementos fundantes do plano de trabalho em questão. 

## Interface
- Texto da diligência
- Informações sobre o plano de trabalho
- Informações sobre cada componente
- Botões de ação
- Histórico de diligências do plano de trabalho 

### Interface do Histórico
O componente deve conter o nome do usuário, data, resumo em 150 primeiros caracteres do texto da diligencia, ordenados pelos últimos três registros. O componente deve possibilitar o reuso em outros locais do sistema.

### Texto da Diligencia
Atualmente já existe um componente de formatação de texto para enviar a diligência, deve-se utilizá-lo. Trata-se de um componente TextField, sem limites de caracteres.

### Botoes de ação
Deve conter um botão para enviar a diligencia e outro para cancelar o envio da diligencia.

### Informações sobre cada componente
Na tela de criação da diligência, haverá um secção com todos os componentes do ente federado com suas respectivas situações. 

### Informações sobre o Plano de Trabalho
Deve ser mostrado o nome do ente federado.

**Comment by decko** [comment]
A funcionalidade está em testes com a área de negócios desde 27/03. Preparar para enviar à Produçao até 06/04
