### ISSUE TITLE
Desenvolvimento VerSNC

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/sistema-nacional-cultura#57]
Eu como gestor do ministério da cultura quero poder pesquisar os cadastros dos sistemas Locais de Cultura de várias formas (filtros e ordenações) para simplificar/viabilizar as atividades rotineiras de gestão dos processos de adesão [e execução do Plano de Trabalho].

**Condições de Satisfação:**
- [x] Visualizar os dados principais de todas as adesões em formato tabular
- [x] Filtrar por município e UF
- [ ] Filtrar a partir de combinação de vários parâmetros (região, situação adesão, ranges de data, componentes, ativo/inativo, etc)
- [x] Ordenar por vários campos (datas, região, UF, situação, etc)
- [ ] Acessar as funções/telas para realização das atividades de gestão
- [ ] Exportar resultados para ODS e CSV
